#!/usr/bin/env python3
"""Rollback-safe user installer for tmuxgate and its Codex MCP registration."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
import datetime as dt
import fcntl
import hashlib
import json
import os
from pathlib import Path
import platform
import re
import secrets
import shlex
import shutil
import stat
import subprocess
import sys
from typing import Mapping, Sequence

if sys.version_info < (3, 11):  # pragma: no cover - cannot run under the test floor
    raise SystemExit("tmuxgate installer: Python 3.11 or newer is required")

import tomllib


MCP_NAME = "tmuxgate"
MCP_PATH = "/mcp"
MCP_TOKEN_ENV = "TMUXGATE_MCP_TOKEN"
MCP_TOOL_TIMEOUT_SECONDS = 604_900
PROFILE_START = "# >>> tmuxgate Codex MCP >>>"
PROFILE_END = "# <<< tmuxgate Codex MCP <<<"
ENV_FILE_HEADER = "# Generated by the tmuxgate installer; contains no credential."
INSTALLER_VERSION = 1


class InstallError(RuntimeError):
    """A user-facing, fail-closed installation error."""


@dataclass(frozen=True, slots=True)
class FileSnapshot:
    """Recoverable state for one non-directory filesystem entry."""

    exists: bool
    kind: str = "missing"
    data: bytes = b""
    target: str = ""
    mode: int = 0o600

    @classmethod
    def capture(cls, path: Path) -> "FileSnapshot":
        try:
            metadata = os.lstat(path)
        except FileNotFoundError:
            return cls(False)
        if stat.S_ISLNK(metadata.st_mode):
            return cls(True, kind="symlink", target=os.readlink(path))
        if stat.S_ISREG(metadata.st_mode):
            return cls(
                True,
                kind="file",
                data=_read_regular_file(path),
                mode=stat.S_IMODE(metadata.st_mode),
            )
        raise InstallError(f"refusing unsupported filesystem entry: {path}")

    def restore(self, path: Path) -> None:
        if not self.exists:
            try:
                path.unlink()
            except FileNotFoundError:
                pass
            return
        if self.kind == "symlink":
            _atomic_symlink(path, self.target)
            return
        if self.kind == "file":
            _atomic_write(path, self.data, self.mode)
            return
        raise AssertionError(f"unknown snapshot kind {self.kind!r}")


@dataclass(frozen=True, slots=True)
class OwnedMutation:
    """A pre/post image that may be rolled back only while still installer-owned."""

    path: Path
    before: FileSnapshot
    after: FileSnapshot

    @classmethod
    def capture(cls, path: Path, before: FileSnapshot) -> "OwnedMutation":
        after = FileSnapshot.capture(path)
        if after == before:
            raise InstallError(f"expected installer mutation did not change {path}")
        return cls(path=path, before=before, after=after)

    def rollback(self) -> None:
        current = FileSnapshot.capture(self.path)
        if current == self.before:
            return
        if current != self.after:
            raise InstallError(
                f"refusing to overwrite a concurrent change while rolling back {self.path}"
            )
        self.before.restore(self.path)
        if FileSnapshot.capture(self.path) != self.before:
            raise InstallError(f"rollback verification failed for {self.path}")


@dataclass(frozen=True, slots=True)
class ProbeResult:
    config_path: Path
    config_present: bool
    state_dir: Path
    token_path: Path
    mcp_url: str
    approval_mode: str | None

    @classmethod
    def from_json(cls, value: object) -> "ProbeResult":
        if not isinstance(value, dict):
            raise InstallError("installed tmuxgate probe returned a non-object")
        expected = {
            "config_path",
            "config_present",
            "state_dir",
            "token_path",
            "mcp_url",
            "approval_mode",
        }
        if set(value) != expected:
            raise InstallError("installed tmuxgate probe returned an unexpected schema")
        config_present = value["config_present"]
        approval_mode = value["approval_mode"]
        if type(config_present) is not bool:
            raise InstallError("installed tmuxgate probe returned an invalid config flag")
        if approval_mode is not None and approval_mode not in {"always", "disabled"}:
            raise InstallError("installed tmuxgate probe returned an invalid approval mode")
        strings = ("config_path", "state_dir", "token_path", "mcp_url")
        if any(not isinstance(value[key], str) or not value[key] for key in strings):
            raise InstallError("installed tmuxgate probe returned an invalid path or URL")
        result = cls(
            config_path=Path(value["config_path"]),
            config_present=config_present,
            state_dir=Path(value["state_dir"]),
            token_path=Path(value["token_path"]),
            mcp_url=value["mcp_url"],
            approval_mode=approval_mode,
        )
        if not result.mcp_url.startswith("http://127.0.0.1:") or not result.mcp_url.endswith(
            MCP_PATH
        ):
            raise InstallError("installed tmuxgate probe returned a non-loopback MCP URL")
        return result


def _read_regular_file(path: Path) -> bytes:
    metadata = os.lstat(path)
    if not stat.S_ISREG(metadata.st_mode):
        raise InstallError(f"refusing non-regular file: {path}")
    if metadata.st_uid != os.geteuid():
        raise InstallError(f"file is not owned by the current user: {path}")
    flags = os.O_RDONLY | getattr(os, "O_CLOEXEC", 0) | getattr(os, "O_NOFOLLOW", 0)
    descriptor = os.open(path, flags)
    try:
        opened = os.fstat(descriptor)
        if not stat.S_ISREG(opened.st_mode) or (
            opened.st_dev,
            opened.st_ino,
        ) != (metadata.st_dev, metadata.st_ino):
            raise InstallError(f"file changed while opening: {path}")
        chunks: list[bytes] = []
        while True:
            chunk = os.read(descriptor, 65_536)
            if not chunk:
                return b"".join(chunks)
            chunks.append(chunk)
    finally:
        os.close(descriptor)


def _fsync_directory(path: Path) -> None:
    descriptor = os.open(
        path,
        os.O_RDONLY | getattr(os, "O_DIRECTORY", 0) | getattr(os, "O_CLOEXEC", 0),
    )
    try:
        os.fsync(descriptor)
    finally:
        os.close(descriptor)


def _atomic_write(path: Path, payload: bytes, mode: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.parent / f".{path.name}.tmuxgate-{secrets.token_hex(8)}.tmp"
    flags = (
        os.O_WRONLY
        | os.O_CREAT
        | os.O_EXCL
        | getattr(os, "O_CLOEXEC", 0)
        | getattr(os, "O_NOFOLLOW", 0)
    )
    descriptor = os.open(temporary, flags, mode)
    try:
        os.fchmod(descriptor, mode)
        offset = 0
        while offset < len(payload):
            written = os.write(descriptor, payload[offset:])
            if written <= 0:
                raise InstallError(f"write made no progress for {path}")
            offset += written
        os.fsync(descriptor)
        os.close(descriptor)
        descriptor = -1
        os.replace(temporary, path)
        _fsync_directory(path.parent)
    finally:
        if descriptor >= 0:
            os.close(descriptor)
        try:
            temporary.unlink()
        except FileNotFoundError:
            pass


def _atomic_symlink(path: Path, target: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.parent / f".{path.name}.tmuxgate-{secrets.token_hex(8)}.tmp"
    try:
        os.symlink(target, temporary)
        os.replace(temporary, path)
        _fsync_directory(path.parent)
    finally:
        try:
            temporary.unlink()
        except FileNotFoundError:
            pass


def _write_owned(
    path: Path,
    payload: bytes,
    mode: int,
    *,
    before: FileSnapshot | None = None,
) -> OwnedMutation | None:
    preimage = FileSnapshot.capture(path) if before is None else before
    expected = FileSnapshot(True, kind="file", data=payload, mode=mode)
    try:
        _atomic_write(path, payload, mode)
    except BaseException as exc:
        current = FileSnapshot.capture(path)
        if current == expected and current != preimage:
            try:
                OwnedMutation(path, preimage, current).rollback()
            except InstallError as rollback_error:
                raise InstallError(f"{exc}; write rollback stopped: {rollback_error}") from exc
        raise
    after = FileSnapshot.capture(path)
    if after == preimage:
        return None
    if after != expected:
        raise InstallError(f"file changed concurrently after installer write: {path}")
    return OwnedMutation(path, preimage, after)


def _symlink_owned(
    path: Path,
    target: str,
    *,
    before: FileSnapshot | None = None,
) -> OwnedMutation | None:
    preimage = FileSnapshot.capture(path) if before is None else before
    expected = FileSnapshot(True, kind="symlink", target=target)
    try:
        _atomic_symlink(path, target)
    except BaseException as exc:
        current = FileSnapshot.capture(path)
        if current == expected and current != preimage:
            try:
                OwnedMutation(path, preimage, current).rollback()
            except InstallError as rollback_error:
                raise InstallError(f"{exc}; symlink rollback stopped: {rollback_error}") from exc
        raise
    after = FileSnapshot.capture(path)
    if after == preimage:
        return None
    if after != expected:
        raise InstallError(f"symlink changed concurrently after installer write: {path}")
    return OwnedMutation(path, preimage, after)


def _ensure_private_directory(path: Path) -> None:
    if not path.is_absolute():
        raise InstallError(f"installer path must be absolute: {path}")
    try:
        metadata = os.lstat(path)
    except FileNotFoundError:
        path.mkdir(parents=True, mode=0o700)
        metadata = os.lstat(path)
    if stat.S_ISLNK(metadata.st_mode) or not stat.S_ISDIR(metadata.st_mode):
        raise InstallError(f"private installer path is not a real directory: {path}")
    if metadata.st_uid != os.geteuid():
        raise InstallError(f"private installer path has the wrong owner: {path}")
    if stat.S_IMODE(metadata.st_mode) != 0o700:
        raise InstallError(f"private installer path must have mode 0700: {path}")


def _ensure_user_directory(path: Path, *, create_mode: int = 0o755) -> None:
    if not path.is_absolute():
        raise InstallError(f"installer path must be absolute: {path}")
    try:
        metadata = os.lstat(path)
    except FileNotFoundError:
        path.mkdir(parents=True, mode=create_mode)
        metadata = os.lstat(path)
    if stat.S_ISLNK(metadata.st_mode) or not stat.S_ISDIR(metadata.st_mode):
        raise InstallError(f"installer path is not a real directory: {path}")
    if metadata.st_uid != os.geteuid():
        raise InstallError(f"installer path has the wrong owner: {path}")
    if stat.S_IMODE(metadata.st_mode) & 0o022:
        raise InstallError(f"installer path must not be group/world writable: {path}")


def _ensure_codex_directory(path: Path) -> None:
    """Create Codex home privately or harden an owner-controlled existing one."""

    if not path.is_absolute():
        raise InstallError(f"installer path must be absolute: {path}")
    try:
        metadata = os.lstat(path)
    except FileNotFoundError:
        path.mkdir(parents=True, mode=0o700)
        metadata = os.lstat(path)
    if stat.S_ISLNK(metadata.st_mode) or not stat.S_ISDIR(metadata.st_mode):
        raise InstallError(f"Codex home is not a real directory: {path}")
    if metadata.st_uid != os.geteuid():
        raise InstallError(f"Codex home has the wrong owner: {path}")
    if stat.S_IMODE(metadata.st_mode) != 0o700:
        print(f"tmuxgate installer: hardening Codex home permissions to 0700: {path}")
        os.chmod(path, 0o700, follow_symlinks=False)
        hardened = os.lstat(path)
        if (
            not stat.S_ISDIR(hardened.st_mode)
            or hardened.st_uid != os.geteuid()
            or stat.S_IMODE(hardened.st_mode) != 0o700
            or (hardened.st_dev, hardened.st_ino) != (metadata.st_dev, metadata.st_ino)
        ):
            raise InstallError(f"could not safely harden Codex home: {path}")


def _child_environment(source: Mapping[str, str] | None = None) -> dict[str, str]:
    environment = dict(os.environ if source is None else source)
    for name in (MCP_TOKEN_ENV, "PYTHONHOME", "PYTHONPATH", "VIRTUAL_ENV"):
        environment.pop(name, None)
    return environment


def _run(
    command: Sequence[str],
    *,
    env: Mapping[str, str] | None = None,
    capture: bool = False,
    label: str,
) -> subprocess.CompletedProcess[str]:
    print(f"tmuxgate installer: {label}", flush=True)
    result = subprocess.run(
        list(command),
        check=False,
        env=_child_environment(env),
        stdin=subprocess.DEVNULL,
        stdout=subprocess.PIPE if capture else None,
        stderr=subprocess.PIPE if capture else None,
        text=True,
    )
    if result.returncode != 0:
        detail = ""
        if capture:
            combined = "\n".join(
                part.strip() for part in (result.stdout, result.stderr) if part.strip()
            )
            if combined:
                detail = f": {combined[-2000:]}"
        raise InstallError(f"{label} failed with exit status {result.returncode}{detail}")
    return result


def build_env_file(token_path: Path) -> bytes:
    """Return a POSIX-shell fragment that reads, validates, and exports the token."""

    quoted_path = shlex.quote(str(token_path))
    text = f"""{ENV_FILE_HEADER}
unset {MCP_TOKEN_ENV} _tmuxgate_mcp_extra
_tmuxgate_mcp_token_file={quoted_path}
if [ -r \"$_tmuxgate_mcp_token_file\" ]; then
    if {{
        IFS= read -r {MCP_TOKEN_ENV} &&
        ! IFS= read -r _tmuxgate_mcp_extra &&
        [ -z \"$_tmuxgate_mcp_extra\" ]
    }} < \"$_tmuxgate_mcp_token_file\"; then
        case ${{{MCP_TOKEN_ENV}}} in
            ????????????????????????????????????????????????????????????????)
                case ${{{MCP_TOKEN_ENV}}} in
                    *[!0123456789abcdef]*) unset {MCP_TOKEN_ENV} ;;
                    *) export {MCP_TOKEN_ENV} ;;
                esac
                ;;
            *) unset {MCP_TOKEN_ENV} ;;
        esac
    else
        unset {MCP_TOKEN_ENV}
    fi
fi
unset _tmuxgate_mcp_token_file _tmuxgate_mcp_extra
"""
    return text.encode("utf-8")


def update_profile(original: bytes, env_path: Path) -> bytes:
    """Add or replace the one managed shell-profile block."""

    try:
        text = original.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise InstallError("shell profile is not valid UTF-8") from exc
    if text.count(PROFILE_START) != text.count(PROFILE_END):
        raise InstallError("shell profile has an incomplete tmuxgate managed block")
    if text.count(PROFILE_START) > 1:
        raise InstallError("shell profile has multiple tmuxgate managed blocks")
    quoted_path = shlex.quote(str(env_path))
    block = (
        f"{PROFILE_START}\n"
        f"if [ -r {quoted_path} ]; then\n"
        f"    . {quoted_path}\n"
        "fi\n"
        f"{PROFILE_END}"
    )
    if PROFILE_START in text:
        pattern = re.compile(
            re.escape(PROFILE_START) + r".*?" + re.escape(PROFILE_END), re.DOTALL
        )
        updated, replacements = pattern.subn(block, text)
        if replacements != 1:
            raise InstallError("could not safely replace tmuxgate profile block")
    else:
        separator = "" if not text or text.endswith("\n\n") else ("\n" if text.endswith("\n") else "\n\n")
        updated = text + separator + block + "\n"
    return updated.encode("utf-8")


def patch_codex_timeout(raw: bytes, *, name: str = MCP_NAME) -> bytes:
    """Set the tool timeout only inside Codex's generated tmuxgate table."""

    try:
        text = raw.decode("utf-8")
        tomllib.loads(text)
    except (UnicodeDecodeError, tomllib.TOMLDecodeError) as exc:
        raise InstallError("Codex config is not valid UTF-8 TOML") from exc
    if not re.fullmatch(r"[A-Za-z0-9_-]+", name):
        raise InstallError("unsafe Codex MCP server name")
    header = re.compile(rf"(?m)^\[mcp_servers\.{re.escape(name)}\][ \t]*(?:#.*)?$")
    matches = list(header.finditer(text))
    if len(matches) != 1:
        raise InstallError(f"expected exactly one [mcp_servers.{name}] table")
    body_start = matches[0].end()
    next_header = re.search(r"(?m)^\s*\[", text[body_start:])
    body_end = len(text) if next_header is None else body_start + next_header.start()
    body = text[body_start:body_end]
    timeout_line = re.compile(r"(?m)^[ \t]*tool_timeout_sec[ \t]*=.*$")
    timeout_matches = list(timeout_line.finditer(body))
    replacement = f"tool_timeout_sec = {MCP_TOOL_TIMEOUT_SECONDS}"
    if len(timeout_matches) > 1:
        raise InstallError("Codex tmuxgate table has duplicate tool_timeout_sec keys")
    if timeout_matches:
        start, end = timeout_matches[0].span()
        new_body = body[:start] + replacement + body[end:]
    else:
        content = body.rstrip(" \t\r\n")
        trailing = body[len(content) :]
        new_body = content + "\n" + replacement + "\n" + trailing.lstrip("\r\n")
    updated = (text[:body_start] + new_body + text[body_end:]).encode("utf-8")
    try:
        parsed = tomllib.loads(updated.decode("utf-8"))
        configured = parsed["mcp_servers"][name]["tool_timeout_sec"]
    except (KeyError, TypeError, tomllib.TOMLDecodeError) as exc:
        raise InstallError("updated Codex config failed validation") from exc
    if configured != MCP_TOOL_TIMEOUT_SECONDS:
        raise InstallError("updated Codex timeout failed validation")
    return updated


def codex_entry_matches(entry: object, *, url: str) -> bool:
    if not isinstance(entry, dict) or entry.get("name") != MCP_NAME:
        return False
    transport = entry.get("transport")
    return bool(
        isinstance(transport, dict)
        and entry.get("enabled") is True
        and entry.get("disabled_reason") is None
        and transport.get("type") == "streamable_http"
        and transport.get("url") == url
        and transport.get("bearer_token_env_var") == MCP_TOKEN_ENV
        and transport.get("http_headers") in (None, {})
        and transport.get("env_http_headers") in (None, {})
    )


def launcher_is_replaceable(
    path: Path,
    *,
    source: Path,
    install_root: Path,
    replace_existing: bool,
) -> bool:
    try:
        metadata = os.lstat(path)
    except FileNotFoundError:
        return True
    if replace_existing:
        return not stat.S_ISDIR(metadata.st_mode)
    if not stat.S_ISLNK(metadata.st_mode):
        return False
    raw_target = Path(os.readlink(path))
    target = raw_target if raw_target.is_absolute() else path.parent / raw_target
    normalized = Path(os.path.normpath(target))
    known = {
        Path(os.path.normpath(source / "bin" / "tmuxgate")),
        Path(os.path.normpath(install_root / "current" / "bin" / "tmuxgate")),
    }
    return normalized in known


def _parse_codex_list(output: str) -> list[object]:
    try:
        value = json.loads(output)
    except json.JSONDecodeError as exc:
        raise InstallError("Codex returned invalid JSON from `mcp list`") from exc
    if not isinstance(value, list):
        raise InstallError("Codex returned a non-list from `mcp list`")
    return value


def _register_codex(
    codex: Path,
    codex_config: Path,
    *,
    url: str,
    replace_conflict: bool,
    backup_dir: Path,
) -> OwnedMutation | None:
    before = FileSnapshot.capture(codex_config)
    if before.exists and before.kind != "file":
        raise InstallError(f"refusing non-regular Codex config: {codex_config}")
    listing = _run(
        (str(codex), "mcp", "list", "--json"),
        capture=True,
        label="checking Codex MCP registrations",
    )
    entries = _parse_codex_list(listing.stdout)
    matches = [entry for entry in entries if isinstance(entry, dict) and entry.get("name") == MCP_NAME]
    if len(matches) > 1:
        raise InstallError("Codex reported duplicate tmuxgate MCP registrations")
    exact = bool(matches and codex_entry_matches(matches[0], url=url))
    if matches and not exact and not replace_conflict:
        raise InstallError(
            "Codex already has a different 'tmuxgate' MCP entry; rerun with --replace-codex"
        )

    stamp = dt.datetime.now(dt.UTC).strftime("%Y%m%dT%H%M%SZ")
    if before.exists and before.kind == "file":
        backup = backup_dir / f"codex-config-{stamp}-{secrets.token_hex(4)}.toml"
        _atomic_write(backup, before.data, 0o600)

    owned: OwnedMutation | None = None
    try:
        if matches and not exact:
            _run(
                (str(codex), "mcp", "remove", MCP_NAME),
                capture=True,
                label="removing conflicting Codex tmuxgate registration",
            )
            owned = OwnedMutation.capture(codex_config, before)
        if not exact:
            _run(
                (
                    str(codex),
                    "mcp",
                    "add",
                    MCP_NAME,
                    "--url",
                    url,
                    "--bearer-token-env-var",
                    MCP_TOKEN_ENV,
                ),
                capture=True,
                label="registering tmuxgate with Codex",
            )
            owned = OwnedMutation.capture(codex_config, before)

        if not codex_config.exists():
            raise InstallError(f"Codex did not create its config file: {codex_config}")
        config_metadata = os.lstat(codex_config)
        if not stat.S_ISREG(config_metadata.st_mode) or config_metadata.st_uid != os.geteuid():
            raise InstallError("Codex config is not a current-user regular file")
        current_config = _read_regular_file(codex_config)
        patched = patch_codex_timeout(current_config)
        if patched != current_config:
            _write_owned(
                codex_config,
                patched,
                stat.S_IMODE(config_metadata.st_mode),
                before=FileSnapshot.capture(codex_config),
            )
            owned = OwnedMutation.capture(codex_config, before)

        verified = _run(
            (str(codex), "mcp", "list", "--json"),
            capture=True,
            label="verifying Codex MCP registration",
        )
        verified_entries = _parse_codex_list(verified.stdout)
        verified_matches = [
            entry
            for entry in verified_entries
            if isinstance(entry, dict) and entry.get("name") == MCP_NAME
        ]
        if len(verified_matches) != 1 or not codex_entry_matches(
            verified_matches[0], url=url
        ):
            raise InstallError("Codex tmuxgate MCP registration did not verify")
        if verified_matches[0].get("tool_timeout_sec") != MCP_TOOL_TIMEOUT_SECONDS:
            raise InstallError("Codex tmuxgate tool timeout did not verify")
        return owned
    except BaseException as exc:
        if owned is not None:
            try:
                owned.rollback()
            except InstallError as rollback_error:
                raise InstallError(f"{exc}; Codex rollback stopped: {rollback_error}") from exc
        raise


def _write_shell_integration(
    env_file: Path,
    profiles: Sequence[Path],
    *,
    token_path: Path,
    backup_dir: Path,
) -> list[OwnedMutation]:
    snapshots = {path: FileSnapshot.capture(path) for path in (env_file, *profiles)}
    existing_env = snapshots[env_file]
    if existing_env.exists and existing_env.kind != "file":
        raise InstallError(f"refusing non-regular Codex environment file: {env_file}")
    if existing_env.exists and not existing_env.data.startswith(ENV_FILE_HEADER.encode("utf-8")):
        raise InstallError(f"refusing to replace an unmanaged environment file: {env_file}")
    stamp = dt.datetime.now(dt.UTC).strftime("%Y%m%dT%H%M%SZ")
    mutations: list[OwnedMutation] = []
    try:
        env_mutation = _write_owned(
            env_file,
            build_env_file(token_path),
            0o600,
            before=existing_env,
        )
        if env_mutation is not None:
            mutations.append(env_mutation)
        for index, profile in enumerate(profiles):
            snapshot = snapshots[profile]
            original = snapshot.data if snapshot.exists else b""
            mode = snapshot.mode if snapshot.exists else 0o600
            if snapshot.exists and snapshot.kind != "file":
                raise InstallError(f"refusing non-regular shell profile: {profile}")
            if snapshot.exists:
                backup = backup_dir / f"profile-{index}-{stamp}-{secrets.token_hex(4)}"
                _atomic_write(backup, snapshot.data, 0o600)
            updated = update_profile(original, env_file)
            profile_mutation = _write_owned(
                profile,
                updated,
                mode,
                before=snapshot,
            )
            if profile_mutation is not None:
                mutations.append(profile_mutation)
        return mutations
    except BaseException as exc:
        rollback_errors: list[str] = []
        for mutation in reversed(mutations):
            try:
                mutation.rollback()
            except InstallError as rollback_error:
                rollback_errors.append(str(rollback_error))
        if rollback_errors:
            raise InstallError(f"{exc}; shell rollback stopped: {'; '.join(rollback_errors)}") from exc
        raise


def _installed_probe(argv: Sequence[str]) -> int:
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument("--config", default=None)
    parser.add_argument("--state-dir", default=None)
    args = parser.parse_args(argv)

    from tmuxgate.config import McpConfig, default_config_path, load_config
    from tmuxgate.runtime import (
        MCP_TOKEN_FILE_NAME,
        default_state_dir,
        ensure_state_directory,
        load_or_create_mcp_token,
    )

    config_path = Path(args.config) if args.config else default_config_path()
    if config_path.exists() or config_path.is_symlink():
        config = load_config(config_path)
        mcp = config.mcp
        approval_mode: str | None = config.broker.approval_mode
        config_present = True
    else:
        mcp = McpConfig()
        approval_mode = None
        config_present = False
    selected_state = Path(args.state_dir) if args.state_dir else default_state_dir(os.environ)
    state_dir = ensure_state_directory(selected_state)
    load_or_create_mcp_token(state_dir)
    payload = {
        "config_path": str(config_path),
        "config_present": config_present,
        "state_dir": str(state_dir),
        "token_path": str(state_dir / MCP_TOKEN_FILE_NAME),
        "mcp_url": f"http://{mcp.host}:{mcp.port}{MCP_PATH}",
        "approval_mode": approval_mode,
    }
    print(json.dumps(payload, sort_keys=True))
    return 0


def _public_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Install tmuxgate for this user and register its embedded MCP server with Codex."
    )
    parser.add_argument("--source", type=Path, required=True, help=argparse.SUPPRESS)
    parser.add_argument("--bin-dir", type=Path, default=None, help="user executable directory")
    parser.add_argument("--codex-bin", type=Path, default=None, help="Codex CLI executable")
    parser.add_argument("--no-codex", action="store_true", help="skip Codex registration")
    parser.add_argument(
        "--no-shell-integration",
        action="store_true",
        help="do not add the token-loader block to Bash profiles",
    )
    parser.add_argument(
        "--replace-existing",
        action="store_true",
        help="replace an unrelated existing tmuxgate launcher",
    )
    parser.add_argument(
        "--replace-codex",
        action="store_true",
        help="replace a conflicting Codex MCP registration named tmuxgate",
    )
    parser.add_argument(
        "--allow-disabled-approvals",
        action="store_true",
        help="acknowledge that the token can execute without terminal approval",
    )
    return parser


def _select_base(environ: Mapping[str, str], name: str, fallback: Path) -> Path:
    value = environ.get(name)
    selected = Path(value) if value else fallback
    if not selected.is_absolute():
        raise InstallError(f"{name} must be an absolute path")
    return selected


def install(args: argparse.Namespace) -> int:
    if sys.version_info < (3, 11):
        raise InstallError("Python 3.11 or newer is required")
    if platform.system() != "Linux":
        raise InstallError("tmuxgate's installer currently supports Linux only")
    if os.geteuid() == 0:
        raise InstallError("do not run the tmuxgate installer as root or with sudo")
    os.umask(0o077)

    source = args.source.resolve()
    if not (source / "pyproject.toml").is_file() or not (source / "src" / "tmuxgate").is_dir():
        raise InstallError(f"not a tmuxgate source tree: {source}")
    home = Path.home()
    data_home = _select_base(os.environ, "XDG_DATA_HOME", home / ".local" / "share")
    config_home = _select_base(os.environ, "XDG_CONFIG_HOME", home / ".config")
    install_root = data_home / "tmuxgate"
    releases = install_root / "releases"
    backups = install_root / "backups"
    bin_dir = args.bin_dir or home / ".local" / "bin"
    if not bin_dir.is_absolute():
        raise InstallError("--bin-dir must be absolute")
    launcher = bin_dir / "tmuxgate"

    _ensure_private_directory(install_root)
    _ensure_private_directory(releases)
    _ensure_private_directory(backups)
    _ensure_user_directory(bin_dir)
    if not launcher_is_replaceable(
        launcher,
        source=source,
        install_root=install_root,
        replace_existing=args.replace_existing,
    ):
        raise InstallError(
            f"refusing to replace unrelated launcher {launcher}; use --replace-existing"
        )

    lock_path = install_root / "install.lock"
    lock_flags = os.O_RDWR | os.O_CREAT | getattr(os, "O_CLOEXEC", 0) | getattr(os, "O_NOFOLLOW", 0)
    lock_descriptor = os.open(lock_path, lock_flags, 0o600)
    release_dir: Path | None = None
    rollback: list[OwnedMutation] = []
    published = False
    committed = False
    try:
        os.fchmod(lock_descriptor, 0o600)
        try:
            fcntl.flock(lock_descriptor, fcntl.LOCK_EX | fcntl.LOCK_NB)
        except BlockingIOError as exc:
            raise InstallError("another tmuxgate installer is already running") from exc

        config_path = config_home / "tmuxgate" / "config.toml"
        config_before = FileSnapshot.capture(config_path)
        if not config_before.exists:
            raise InstallError(
                f"configuration not found: {config_path}; create and validate it before installing"
            )
        if config_before.kind != "file":
            raise InstallError(f"refusing non-regular tmuxgate configuration: {config_path}")
        release_id = dt.datetime.now(dt.UTC).strftime("%Y%m%dT%H%M%SZ") + "-" + secrets.token_hex(4)
        release_dir = releases / release_id
        release_dir.mkdir(mode=0o700)
        venv_python = release_dir / "bin" / "python"
        venv_tmuxgate = release_dir / "bin" / "tmuxgate"

        _run(
            (sys.executable, "-m", "venv", str(release_dir)),
            label="creating isolated Python environment",
        )
        pip_env = dict(os.environ)
        pip_env["PIP_DISABLE_PIP_VERSION_CHECK"] = "1"
        _run(
            (
                str(venv_python),
                "-m",
                "pip",
                "install",
                "--no-input",
                "--no-cache-dir",
                str(source),
            ),
            env=pip_env,
            label="installing tmuxgate and runtime dependencies",
        )
        _run(
            (str(venv_python), "-c", "import mcp, uvicorn, tmuxgate"),
            capture=True,
            label="verifying installed Python imports",
        )
        _run((str(venv_tmuxgate), "--version"), capture=True, label="checking installed version")
        _run((str(venv_tmuxgate), "--help"), capture=True, label="checking installed CLI")
        _run(
            (str(venv_tmuxgate), "--config", str(config_path), "config", "check"),
            capture=True,
            label="validating existing tmuxgate configuration",
        )

        probe_command = [str(venv_python), str(source / "scripts" / "install.py"), "--installed-probe"]
        probe_command.extend(("--config", str(config_path)))
        probe = _run(probe_command, capture=True, label="preparing tmuxgate MCP credential")
        try:
            probe_result = ProbeResult.from_json(json.loads(probe.stdout))
        except json.JSONDecodeError as exc:
            raise InstallError("installed tmuxgate probe returned invalid JSON") from exc
        if FileSnapshot.capture(config_path) != config_before:
            raise InstallError("existing tmuxgate configuration changed during installation")
        if (
            not args.no_codex
            and probe_result.approval_mode == "disabled"
            and not args.allow_disabled_approvals
        ):
            raise InstallError(
                "approval_mode is disabled; review the security impact and rerun with "
                "--allow-disabled-approvals, or set approval_mode to 'always'"
            )

        if not args.no_codex:
            codex = args.codex_bin or (Path(found) if (found := shutil.which("codex")) else None)
            if codex is None:
                raise InstallError("Codex CLI was not found; use --no-codex to skip registration")
            if not codex.is_absolute():
                raise InstallError("--codex-bin must be absolute")
            codex_home = _select_base(os.environ, "CODEX_HOME", home / ".codex")
            _ensure_codex_directory(codex_home)
            codex_config = codex_home / "config.toml"
            codex_mutation = _register_codex(
                codex,
                codex_config,
                url=probe_result.mcp_url,
                replace_conflict=args.replace_codex,
                backup_dir=backups,
            )
            if codex_mutation is not None:
                rollback.append(codex_mutation)

        if not args.no_codex and not args.no_shell_integration:
            shell_config_dir = config_home / "tmuxgate"
            _ensure_private_directory(shell_config_dir)
            env_file = shell_config_dir / "codex-env.sh"
            shell = Path(os.environ.get("SHELL", "")).name
            if shell not in {"bash", ""}:
                raise InstallError(
                    f"automatic shell integration supports Bash, not {shell!r}; use --no-shell-integration"
                )
            profiles = (home / ".bashrc", home / ".profile")
            profile_mutations = _write_shell_integration(
                env_file,
                profiles,
                token_path=probe_result.token_path,
                backup_dir=backups,
            )
            rollback.extend(profile_mutations)

        current = install_root / "current"
        current_before = FileSnapshot.capture(current)
        launcher_before = FileSnapshot.capture(launcher)
        # From this point a process could observe the new release even if a
        # directory fsync or later step fails, so failure cleanup must retain it.
        published = True
        current_mutation = _symlink_owned(
            current,
            f"releases/{release_id}",
            before=current_before,
        )
        if current_mutation is not None:
            rollback.append(current_mutation)
        launcher_mutation = _symlink_owned(
            launcher,
            str(current / "bin" / "tmuxgate"),
            before=launcher_before,
        )
        if launcher_mutation is not None:
            rollback.append(launcher_mutation)

        manifest = {
            "installer_version": INSTALLER_VERSION,
            "installed_at": dt.datetime.now(dt.UTC).isoformat(),
            "source": str(source),
            "mcp_url": probe_result.mcp_url,
            "launcher": str(launcher),
        }
        manifest_path = install_root / "install.json"
        manifest_mutation = _write_owned(
            manifest_path,
            (json.dumps(manifest, indent=2, sort_keys=True) + "\n").encode("utf-8"),
            0o600,
        )
        if manifest_mutation is not None:
            rollback.append(manifest_mutation)
        committed = True
        rollback.clear()
        release_dir = None

        print()
        print(f"tmuxgate installed: {launcher}")
        print(f"Codex MCP endpoint: {probe_result.mcp_url}")
        print("The application was not started in the background.")
        if not args.no_codex:
            if args.no_shell_integration:
                print(f"Before launching Codex, export {MCP_TOKEN_ENV} from {probe_result.token_path}.")
            else:
                print("Open a new Bash shell and restart Codex so it inherits the MCP token.")
        print("Start the foreground application in its controlling terminal with: tmuxgate")
        if probe_result.approval_mode == "disabled":
            print(
                "WARNING: approval_mode is disabled; possession of the MCP token permits execution "
                "without a per-request terminal approval.",
                file=sys.stderr,
            )
        return 0
    except BaseException:
        if committed:
            raise
        rollback_errors: list[str] = []
        for mutation in reversed(rollback):
            try:
                mutation.rollback()
            except Exception as rollback_error:
                rollback_errors.append(f"{mutation.path}: {rollback_error}")
        for error in rollback_errors:
            print(f"tmuxgate installer: rollback warning: {error}", file=sys.stderr)
        if (
            release_dir is not None
            and not published
            and release_dir.parent == releases
            and release_dir.exists()
        ):
            shutil.rmtree(release_dir)
        elif release_dir is not None and published:
            print(
                f"tmuxgate installer: retaining published release after failure: {release_dir}",
                file=sys.stderr,
            )
        raise
    finally:
        os.close(lock_descriptor)


def main(argv: Sequence[str] | None = None) -> int:
    selected = list(sys.argv[1:] if argv is None else argv)
    if selected and selected[0] == "--installed-probe":
        return _installed_probe(selected[1:])
    args = _public_parser().parse_args(selected)
    try:
        return install(args)
    except InstallError as exc:
        print(f"tmuxgate installer: {exc}", file=sys.stderr)
        return 1
    except KeyboardInterrupt:
        print("tmuxgate installer: interrupted; previous installation retained", file=sys.stderr)
        return 130


if __name__ == "__main__":
    raise SystemExit(main())
